### ISSUE TITLE
Cargo plugin does not work remotely

### ISSUE THREAD

**Issue by Cousjava** [Cousjava/payara-maven-test#3]
Fails with
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at fish.payara.jonathan.it.WebappIT.callIndexPage(WebappIT.java:26)

Occurs using both my branch and OndrejM's (#1)

Using:
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-72-generic", arch: "amd64", family: "unix"
Payara - 4.1.1.172 snapshot, recent build form master

**Comment by OndroMih** [comment]
Connection refused doesn't mean that the plugin isn't working, but that either
- nothing is running on the admin host and port (localhost:4848 by default)
- Payara server is running on a different port
- the plugin is trying to connect to another port (defined by `payara.hostname` and `payara.adminPort`)
- firewall is blocking the connection

Are you able to access Admin Console? What's the URL you use in the browser?

What's your command to run maven? Is it possible that your settings.xml overwrites the above properties? Try running maven in debug (using `mvn --debug ...`), find the above properties in the debug output and check what's their value.

**Comment by OndroMih** [comment]
Did you start Payara server by yourself before running maven? The remote configuration expects that the server is running before the test is started. Only local configuration can start the server.

**Comment by Cousjava** [comment]
Seems to be working fine now, don't know why it failed before
